language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
script:
  - npm run test
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
