sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
script:
  - npm run test:single
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  only:
    - master