sudo: false
language: node_js
node_js:
  - "4"
cache:
  directories:
    - node_modules
notifications:
  email: false
script:
  - npm run test:single
  - npm run check-coverage
after_success:
  - npm run report-coverage
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  only:
    - master